# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dae4aa5d91300ea92e0bbc245a611f6d8faed87b302294dc71dc12a28d182ce7665e3b41f1b391b7f9fc3aff79111679f48baf80abee6c22835705ab66469243

test:
  secret_key_base: 37af65af3c84e8fcf76166037ff9f3234c254f2541a134eabf8a34cd264ade3e17275d4521f96b140677444ebb2fb2570dd621dda3f17e467796916d4e98ca92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
